# .github/workflows/seat_watch.yml
name: NU Banner Seat Watch

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch seat status
        id: fetch
        run: |
          python seat-watch-pw.py > status.txt
          echo "::set-output name=body::$(cat status.txt)"

      - name: Send email via SendGrid
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "NU Banner Seat/Waitlist Status"
          body:   ${{ steps.fetch.outputs.body }}
          to:     ${{ secrets.EMAIL_TO }}
          from:   ${{ secrets.EMAIL_FROM }}
