name: NU Banner Seat Watch

on:
  schedule:
    - cron: '*/15 * * * *'   # every 5 minutes
  workflow_dispatch:       # also allow manual run

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run Seat Watch script
        env:
          # Banner cookies
          JSESSIONID:      ${{ secrets.JSESSIONID }}
          NUBANNER_COOKIE: ${{ secrets.NUBANNER_COOKIE }}
          # SMTP credentials
          SMTP_USER:       ${{ secrets.SMTP_USER }}
          SMTP_PASS:       ${{ secrets.SMTP_PASS }}
          EMAIL_TO:        ${{ secrets.EMAIL_TO }}
        run: python seat-watch-pw.py
