name: NU Banner Seat Watch

on:
  schedule:
    - cron: '*/02 * * * *'

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch seat status
        id: fetch
        env:
          JSESSIONID:      ${{ secrets.JSESSIONID }}
          NUBANNER_COOKIE: ${{ secrets.NUBANNER_COOKIE }}
        run: |
          python seat-watch-pw.py > status.txt
          # this lets us carry the fetched text into the next step
          echo "::set-output name=body::$(<status.txt)"

      - name: Send email via SendGrid
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "NU Banner Seat/Waitlist Status"
          body:   ${{ steps.fetch.outputs.body }}
          to:     ${{ secrets.EMAIL_TO }}
          from:   ${{ secrets.EMAIL_FROM }}
